server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zixishi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    password:
    port: 6379
mybatis:
  mapper-locations: com.zixishi.zhanwei.mapper/*.xml
  ### 别名配置
  type-aliases-package: com.zixishi.zhanwei.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ### 驼峰命名配置
    map-underscore-to-camel-case: true
attachment:
  home: D:/myproject/MyBiYeSheJi2/src/main/java/com/zixishi/zhanwei/config/image
